---

- name: Remove Ombi Container
  docker_container:
    name: ombi
    state: absent

- name: Deploy Ombi Container
  docker_container:
    name: ombi
    image: lsiodev/ombi-preview
    pull: yes
    cpu_shares: 128
    published_ports:
      - "{{ports}}3579:3579"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    volumes:
      - /opt/appdata/ombiv3:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: plexguide
        aliases:
          - ombi
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:ombi.{{domain}}"
      traefik.port: "3579"