---
- name: Remove Sonarr Container
  docker_container:
    name: sonarr
    state: absent

- name: Deploy Sonarr Container
  docker_container:
    name: sonarr
    image: hotio/suitarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}8989:8989"
    env:
      APP: sonarr
      VERSION: stable
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    networks:
      - name: plexguide
        aliases:
          - sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/unionfs:/unionfs
      - /mnt/sab/complete:/complete
      - /mnt/nzbget/completed:/completed
      - /mnt/deluge/downloaded:/downloaded
      - /mnt/torrentvpn/downloaded:/data/completed
      - /mnt/rutorrents/downloads/incoming:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:sonarr.{{domain}}"
      traefik.port: "8989"
