---
- name: Remove Radarr Container
  docker_container:
    name: radarr
    state: absent

- name: Deploy Radarr Container
  docker_container:
    name: radarr
    image: hotio/suitarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}7878:7878"
    env:
      APP: radarr
      VERSION: stable
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: plexguide
        aliases:
          - radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/unionfs:/unionfs
      - /mnt/torrentvpn/downloaded:/data/completed
      - /mnt/sab/complete:/complete
      - /mnt/nzbget/completed:/completed
      - /mnt/rutorrents/downloads:/downloads
      - /mnt/deluge/downloaded:/downloaded
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:radarr.{{domain}}"
      traefik.port: "7878"
