---
  - name: Install common packages
    apt: "name={{item}} state=installed"
    with_items:
      - fuse
      - nano
      - fail2ban
      - wget
      - lsb-release
      - figlet
      - update-motd
      - update-notifier-common
      - unionfs-fuse
      - software-properties-common
      - unrar
      - unzip
      - glances
      - python-pip
      - python3-pip
      - python-passlib
      - zip
      - curl
      - man-db
      - htop
      - openssh-server
      - dirmngr
      - npm
      - zip
      - apt-transport-https
      - ca-certificates
      - tree
      - ncdu
      - ctop
    ignore_errors: yes

  - debug: msg="You May Get An Error Notice, Ignore the Error!"

  - name: Ansible-ToolBox from https://github.com/larsks/ansible-toolbox
    shell: pip install git+https://github.com/larsks/ansible-toolbox
    ignore_errors: yes

  - name: Remove Symbolic if it exists
    shell: unlink /etc/ansible/roles
    ignore_errors: yes

  - name: Remove Folder if it exists
    shell: rm -r /etc/ansible/roles
    ignore_errors: yes

  - name: Create Symbolic Link for Ansible-ToolBox
    shell: ln -s /opt/plexguide/ansible/roles /etc/ansible/

  #- name: Install ctop
    #get_url:
      #url:  https://github.com/bcicen/ctop/releases/download/v0.7/ctop-0.7-linux-amd64
      #dest: /usr/local/bin/ctop
      #mode: 0755
      #owner: root
      #group: root
      #force: yes
    #ignore_errors: yes
