---

##### Need to make sure to run:-
##### /sbin/modprobe iptable_mangle

- name: Create Basic directories for Torrents
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /mnt/torrentvpn


- name: Create Basic directories for DelugeVPN
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /opt/appdata/vpn
    - /opt/appdata/vpn/deluge
    - /opt/appdata/vpn/deluge/config
    - /opt/appdata/vpn/deluge/config/openvpn

########## Moving certs to config file
- name: Copy default ovpn cert
  template:
    src: "ca.rsa.2048.crt"
    dest: "/opt/appdata/vpn/deluge/config/openvpn/ca.rsa.2048.crt"
    force: yes

- name: Copy default ovpn pem
  template:
    src: "crl.rsa.2048.pem"
    dest: "/opt/appdata/vpn/deluge/config/openvpn/crl.rsa.2048.pem"
    force: yes

- name: Copy default ovpn file
  template:
    src: "netherlands.ovpn"
    dest: "/opt/appdata/vpn/deluge/config/openvpn/netherlands.ovpn"
    force: yes

########## Remove old existing config file
- name: Removing all ovpn files
  shell: rm -r  /opt/appdata/vpn/deluge/config/openvpn/*.ovpn

########## Remote Server selection

- name: Choose Server
  pause:
    prompt: " \n
      What PIA server would you like to use?\n
         \n
       france, germany, israel, montreal, netherlands,\n
       romainia, sweden, switzerland, toronto or vancouver.\n
       \n
       "
  register: server

- debug: msg="Using server in {{server.user_input}} "

- name: "Install {{server.user_input}} openvpn file"
  template:
    src: "{{server.user_input}}.ovpn"
    dest: "/opt/appdata/vpn/deluge/config/openvpn/{{server.user_input}}.ovpn"
    force: yes

########## Run iptable_mangle command
- name: Making sure iptable is set
  shell: /sbin/modprobe iptable_mangle

######### Remove previous containers
- name: Remove Rtorrent Container
  docker_container:
    name: rtorrentvpn
    state: absent

- name: Remove Deluge Container
  docker_container:
    name: deluge
    state: absent

- name: Remove DelugeVPN Container
  docker_container:
    name: delugevpn
    state: absent

######## Deploy new container
- name: Deploy Deluge Container
  docker_container:
    name: delugevpn
    image: binhex/arch-delugevpn
    pull: yes
    cpu_shares: 256
#    network_mode: "bridge"
    capabilities:
      - NET_ADMIN
    published_ports:
      - "{{ports}}8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    env:
      PUID: "1000"
      PGID: "1000"
#      UMASK: "0022"
      NAME_SERVERS: 209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4
      VPN_ENABLED: "yes"
      VPN_USER: "{{vpnuser}}"
      VPN_PASS: "{{vpnpassword}}"
      VPN_PROV: pia
      STRICT_PORT_FORWARD: "yes"
      STRONG_CERTS: "no"
      ENABLE_PRIVOXY: "yes"
      DEBUG: false
      VPN_PORT: 1198
      VPN_PROTOCOL: udp
      VPN_DEVICE_TYPE: tun
      LAN_NETWORK: "{{subnet}}"
      HTTPS_METHOD: noredirect
    volumes:
      - /opt/appdata/vpn/deluge/config:/config
      - /mnt/torrentvpn/temp:/data/incomplete
      - /mnt/torrentvpn/downloaded:/data/completed
      - /mnt/torrentvpn/.torrent:/data/torrents
      - /mnt/torrentvpn/.watched:/data/watched
      - /etc/localtime:/etc/localtime:ro
      - /mnt/unionfs/:/unionfs
    restart_policy: unless-stopped
    state: started
    networks:
      - name: plexguide
        aliases:
          - delugevpn
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:delugevpn.{{domain}}"
      traefik.port: "8112"
