---
- name: Remove Resilio Container
  docker_container:
    name: resilio
    state: absent

- name: Deploy Resilio Container
  docker_container:
    name: resilio
    image: linuxserver/resilio-sync
    pull: yes
    cpu_shares: 256
    published_ports:
      - "55555:55555"
      - "{{ports}}8888:8888"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    networks:
      - name: plexguide
        aliases:
          - resilio
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/resilio:/config
      - /mnt:/sync
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:resilio.{{domain}}"
      traefik.port: "8888"