---
- name: Remove Ubooquity Container
  docker_container:
    name: ubooquity
    state: absent

- name: Deploy Ubooquity Container
  docker_container:
    name: ubooquity
    image: linuxserver/ubooquity
    pull: yes
    cpu_shares: 256
    published_ports:
    - "{{ports}}2202:2202"
    - "2203:2203"
    env:
      APP: ubooquity
      VERSION: stable
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: plexguide
        aliases:
          - ubooquity
    volumes:
    - /opt/appdata/ubooquity:/config
    - /mnt/unionfs/books:/books
    - /mnt/unionfs/comics:/comics
    - /mnt/unionfs/raw:/files
    - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:ubooquity.{{domain}}"
      traefik.port: "2202"
