---

- name: Remove Organizr Container
  docker_container:
    name: organizr
    state: absent

- name: Deploy Organizr Container
  docker_container:
    name: organizr
    image: lsiocommunity/organizr
    pull: yes
    cpu_shares: 128
    published_ports:
      - "{{ports}}8020:80"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    volumes:
      - /opt/appdata/organizr:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: plexguide
        aliases:
          - organizr
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:organizr.{{domain}}"
      traefik.port: "80"