---
- name: Remove Medusa Container
  docker_container:
    name: medusa
    state: absent

- name: Create Medusa Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /mnt/medusa
    - /mnt/medusa/downloads

- name: Deploy Medusa Container
  docker_container:
    name: medusa
    image: "linuxserver/medusa"
    pull: yes
    published_ports:
      - "{{ports}}8081:8081"
    volumes:
      - /opt/appdata/medusa:/config
      - /mnt/medusa/downloads:/downloads
      - /mnt/unionfs/:/tv
      - /mnt:/test
    cpu_shares: 256
    env:
      PUID: 1000
      PGID: 1000
      HTTPS_METHOD: noredirect
    networks:
      - name: plexguide
        aliases:
          - medusa
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:medusa.{{domain}}"
      traefik.port: "8081"
