---

- name: Remove HTPCManager Container
  docker_container:
    name: htpcmanager
    state: absent

- name: Deploy HTPCManager Container
  docker_container:
    name: htpcmanager
    image: linuxserver/htpcmanager
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}8085:8085"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    volumes:
      - "/opt/appdata/htpcmanager:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - htpcmanager
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:htpcmanager.{{domain}}"
      traefik.port: "8085"
    restart_policy: always
    state: started
